//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrdApproval
    {
        public int PlantID { get; set; }
        public int RefNo { get; set; }
        public int AppID { get; set; }
        public string AppCode { get; set; }
        public int AppType { get; set; }
        public string FirstApp { get; set; }
        public string SecondApp { get; set; }
        public string FirstStatus { get; set; }
        public string SecondStatus { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> SecondDate { get; set; }
        public string FirstRemarks { get; set; }
        public string SecondRemarks { get; set; }
    }
}
