//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrdMachine
    {
        public int MachineID { get; set; }
        public string MachineCode { get; set; }
        public string MachineName { get; set; }
        public int PlantName { get; set; }
        public Nullable<int> MachineType { get; set; }
        public string Flag { get; set; }
    }
}
