//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrdPurchase
    {
        public int PlantID { get; set; }
        public int ReceivedTranNo { get; set; }
        public Nullable<int> LocalForeign { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<int> RefOrderNo { get; set; }
        public Nullable<int> RefInvoice { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string IndentNo { get; set; }
        public Nullable<int> LCNo { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
