//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrdParameter
    {
        public int Code { get; set; }
        public string Description { get; set; }
        public string ParamCode { get; set; }
        public string ParentCode { get; set; }
        public Nullable<int> ParamValue { get; set; }
        public Nullable<int> SubValue { get; set; }
        public string SubCode { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
