//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrdRequestMaster
    {
        public int PlantID { get; set; }
        public int ReqID { get; set; }
        public Nullable<System.DateTime> ReqDate { get; set; }
        public string RefNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
