//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrdReceiveMaster
    {
        public int PlantID { get; set; }
        public int ReqRecID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public Nullable<int> TypeCode { get; set; }
        public string UserNote { get; set; }
        public string AppBy { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string AppFlag { get; set; }
        public string AppRemarks { get; set; }
        public string AppBy2 { get; set; }
        public Nullable<System.DateTime> AppDate2 { get; set; }
        public string AppFlag2 { get; set; }
        public string AppRemarks2 { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
