//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrdSupplier
    {
        public int SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string SupplierAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Status { get; set; }
        public Nullable<int> ZoneCode { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string MultiFlag { get; set; }
        public string Remarks { get; set; }
        public string ContactPerson { get; set; }
        public string TINNo { get; set; }
        public string BINNo { get; set; }
        public string VATRegNo { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CraeteDate { get; set; }
    }
}
