//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sBenificiary
    {
        public int BenificiaryID { get; set; }
        public string BenificiaryName { get; set; }
        public Nullable<int> DesigID { get; set; }
        public string ContactNo { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> PlantFlag { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
    }
}
