//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sDocument
    {
        public int ID { get; set; }
        public int WarehouesID { get; set; }
        public string DocCode { get; set; }
        public string DocType { get; set; }
        public string DocDescription { get; set; }
        public Nullable<System.DateTime> Endof { get; set; }
        public Nullable<int> DocStart { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> DocEnd { get; set; }
        public Nullable<int> CurrNo { get; set; }
        public int MaxLength { get; set; }
        public string MidCode { get; set; }
        public string Narration { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}
