//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sPageName
    {
        public int SLNo { get; set; }
        public string FileName { get; set; }
        public string ContName { get; set; }
        public string PageName { get; set; }
        public string Status { get; set; }
        public string Used { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<int> PageType { get; set; }
    
        public virtual sMenu sMenu { get; set; }
    }
}
