//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sUnit
    {
        public int Id { get; set; }
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> MeasurmentValue { get; set; }
        public Nullable<int> ConvertValue { get; set; }
    }
}
